name: "ðŸ¦‰ translations"

on:
  push:
    paths:
      - po/**

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-files:
    name: "ðŸ¦‰ translations"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Cache dependencies"
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wget curl torsocks zsync gettext
          version: 1.0

      - name: "Install AM ðŸŽ"
        run: |
          sudo systemctl enable tor.service || systemctl enable tor.service
          sudo systemctl restart tor.service && wait || systemctl restart tor.service && wait
          chmod +x ./INSTALL
          sudo ./INSTALL 2> /dev/null || ./INSTALL

      # For now until translations are merged to AM
      # We need to overwrite installed am
      # And include translation files
      - name: "Get translations from outside"
        run: |
          cd /tmp/
          # Clone repo with localization
          git clone https://github.com/oSoWoSo/AM am-translations
          cd am-translations
          # Copy source and translated files
          cp -r po /opt/am/
          # Copy translated modules
          cp -r modules /opt/am/
          # Copy am
          cp APP-MANAGER /opt/am/
          # Just for sure
          chmod a+x /opt/am/APP-MANAGER

      - name: "Regen"
        run: |
          am --translate
          cp -r /opt/am/po ./
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          ls
          echo '----------------------------------------------------------------------------'
          ls -R po/
          echo '----------------------------------------------------------------------------'
          git add po/*
          git add po/LINGUAS po/*.po po/*.pot
          git add po/usr/share/locale/*
          git rm po/*.po~

      - name: "Push to Source"
        run: |
          git config --global user.name "web-flow"
          git config --global user.email "noreply@github.com"
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "Update translations"
            git push && echo "Sync to Source succeeded" >> $GITHUB_STEP_SUMMARY
          fi
